### ISSUE TITLE
Compilation fails with sfml 2.3

### ISSUE THREAD

**Issue by repagh** [Sonkun/python-sfml#132]
I tried on Linux (Fedora 22) and OSX (with homebrew), and got the following

```
cythoning src/sfml/graphics/graphics.pyx to src/sfml/graphics/graphics.cpp

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern from "pysfml/window/window_api.h":
    cdef void import_sfml__window()

    cdef VideoMode wrap_videomode(sf.VideoMode *p, bint d)
    cdef ContextSettings wrap_contextsettings(sf.ContextSettings *v)
    cdef Pixels wrap_pixels(Uint8 *p, unsigned int w, unsigned int h)
        ^
------------------------------------------------------------

include/Includes/pysfml/window.pxd:32:9: 'Pixels' is not a type identifier
```

**Comment by kerokeroloid** [comment]
I can confirm that the same error occurs on Manjaro.

**Comment by dewyatt** [comment]
Quick fix is to revert to commit aed55c8

**Comment by erickvermot** [comment]
Quick fix 2:
Reverting to previous commit is not a good option, since it prevents users to change pixels using simple arrays and memoryviews, since Pixels is not meant to be used directly.
Commenting line 32 from window.pdx
#    cdef Pixels wrap_pixels(Uint8 *p, unsigned int w, unsigned int h)
solves it and allows the changes to take place, making it possible to work with pySFML modifiyng pixels using numpy for example.

**Comment by russellballestrini** [comment]
Thank you @erickvermot and @TheZoq2 for the work around.  +1 helped me for sure!
