### ISSUE TITLE
Windows x64 setup.py error (system.pyx no such file or directory)

### ISSUE THREAD

**Issue by Boris-Barboris** [Sonkun/python-sfml#137]
Using Cython 0.19.2, Python 3.3, Windows SDK 7.1. host OS - Windows 8.1
Following instructions from http://www.python-sfml.org/download.html#windows
Executing 'python setup.py install' from SDK command line (DISTUTILS_USE_SDK=1, /x64, /release config) while being in the freshly-cloned directory.
output:

```
C:\Heap\programms\python-sfml-master>python setup.py install  
running install  
running build  
running build_py  
creating build  
creating build\lib.win-amd64-3.3  
creating build\lib.win-amd64-3.3\sfml  
copying src\sfml\sf.py -> build\lib.win-amd64-3.3\sfml  
copying src\sfml\__init__.py -> build\lib.win-amd64-3.3\sfml  
running build_ext  
cythoning system.pyx to system.cpp  
error: C:\Heap\programms\python-sfml-master\system.pyx: No such file or directory  
```

Am I perhaps missing something in the installation process?

**Comment by Ryozuki** [comment]
I have the same problem, running python 3.5.2, Cython 0.25.2, Windows 10

`python setup.py install
running install
running build
running build_py
running build_ext
cythoning system.pyx to system.cpp
error: [Errno 2] No such file or directory: 'C:\\Users\\ryo\\Desktop\\python\\python-sfml\\system.pyx'`

**Comment by Sonkun** [comment]
It's a known error. I already fixed it, will push it shortly (with a couple of Windows fixes).

**Comment by Sonkun** [comment]
Fixed by d9b1362.

To compile on Windows, you must:
1) have the corresponding Microsoft compiler installed (it must match the compiler version of your installation of Python, for instance, Python 3.6 was compiled with MSVC 14.0 which is installed alongside with Visual Sutdio 2015)
2) download a compiled version of SFML (from website) that match both the compiler version and the targeted architecture (x86 or x64)
3) open command-line terminal and configure your compilation environment with vsvarsall.bat  (unnecessary sometimes, with recent versions of VS and Python)
4) type `python setup.py --include-dirs path\to\sfml\headers --library-dirs path\to\sfml\libs`

Tell me if you run across any problem.

**Comment by Ryozuki** [comment]
Yes, i got this error:

```
python setup.py install --include-dirs C:\SFML-2.4.1\include\SFML --library-dirs C:\SFML-2.4.1\lib
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --include-dirs not recognized
```

**Comment by Sonkun** [comment]
Try the following
```
python setup.py build_ext --include-dirs C:\SFML-2.4.1\include --library-dirs C:\SFML-2.4.1\lib
python setup.py install
```

**Comment by Sonkun** [comment]
Also, use SFML v2.3.2. I will update these bindings to latest SFML version as soon as I finish to setup CI and rewrite website.

**Comment by Ryozuki** [comment]
It worked, thanks a lot.
@Sonkun, also another question if you don't mind, is pysfml going to be uploaded to pip?
pip couldn't find it when i tried to install from it.

**Comment by Sonkun** [comment]
@Ryozuki Glad to hear it works. Uploading pySFML to pipy is planned. The recent commits already made it pip installable. For instance, instead of cloning the repo, you can type `pip+https://github.com/Sonkun/python-sfml#egg=pySFML`.
