### ISSUE TITLE
Immovable sprites?

### ISSUE THREAD

**Issue by PythonFanboy** [Sonkun/python-sfml#144]
Well, there is `Sprite.move()` method, but it requires to create a tuple on each frame, wasting memory.

It's also possible to do `sprite.position += (10, 0)`, but this also creates an unnecessary tuple.

Would be great if something simple as that worked:

    sprite.position.x += 5

**Comment by Sonkun** [comment]
There's got to be a "copy" somewhere involving y since SFML doesn't provide a direct accessors for Y.

Also, Vector2 objects have to been seen immutable (they're technically not because this is Python). Your statement `sprite.position.y` can't work because you operate on a copy of position. 

In general, if you need arithmetic, use sf.Vector2, if you don't, just use tuples. Copies are inevitable in this scenario. And don't worry too much about performance, it's fast enough for most of scenario.
